version: '3.8'

services:
  angular:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    tty: true
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  dotnet:
    image: "mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm"
    tty: true
    volumes:
      - .:/workspace:cached
      - ${HOME}/.aspnet/https:/home/vscode/.aspnet/https:cached
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    command: sleep infinity